#!/usr/bin/env python3
"""
Regenerate the OSD element table of mynav-tools/osd-layout.html from src/main/io/osd.h.

The INAV CLI addresses OSD elements by their index in osd_items_e (osd_layout <layout> <item> ...),
so the layout tool needs the exact order of that enum. Run this after any change to it:

    python3 mynav-tools/update-osd-items.py
"""

import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS)
OSD_H = os.path.join(REPO, "src", "main", "io", "osd.h")
HTML = os.path.join(TOOLS, "osd-layout.html")
BLOCK = re.compile(r"// OSD_ITEMS_BEGIN.*?// OSD_ITEMS_END", re.S)


def read_items():
    with open(OSD_H) as f:
        source = f.read()

    match = re.search(r"typedef\s+enum\s*\{(?P<body>[^}]*)\}\s*osd_items_e\s*;", source)
    if not match:
        sys.exit("osd_items_e not found in " + OSD_H)

    body = re.sub(r"/\*.*?\*/", "", match.group("body"), flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    if re.search(r"^\s*#", body, flags=re.M) or "=" in body:
        sys.exit("osd_items_e has conditionals or explicit values: its indices would not be fixed")

    names = [name.strip() for name in body.split(",") if name.strip()]
    if not names or names[-1] != "OSD_ITEM_COUNT":
        sys.exit("osd_items_e must end with OSD_ITEM_COUNT")
    return names[:-1]


def main():
    items = read_items()
    lines = ["// OSD_ITEMS_BEGIN: generated by update-osd-items.py from src/main/io/osd.h, do not edit",
             "const OSD_ITEMS = ["]
    lines += ['  "%s", // %d' % (name, index) for index, name in enumerate(items)]
    lines += ["];", "// OSD_ITEMS_END"]

    with open(HTML) as f:
        html = f.read()
    if not BLOCK.search(html):
        sys.exit("OSD_ITEMS_BEGIN/OSD_ITEMS_END markers not found in " + HTML)
    html = BLOCK.sub(lambda _: "\n".join(lines), html, count=1)
    with open(HTML, "w") as f:
        f.write(html)

    print("%d OSD elements written to %s (last: %d %s)" % (len(items), HTML, len(items) - 1, items[-1]))


if __name__ == "__main__":
    main()
